stages:
  - build
  - style
  - test
  - deploy

build_simple_bash_utils:
  stage: build
  tags:
    - build
  script:
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  after_script:
    - if [ "$CI_JOB_STATUS" = "success" ]; then
        sh src/tg.sh "DO6 CI/CD: Стадия Build успешно завершена!"
      else
        sh src/tg.sh "DO6 CI/CD: Ошибка на стадии Build!"
      fi
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

style-test:
  stage: style
  tags:
    - style
  script:
    - cd src
    - ./test_style.sh
  after_script:
    - if [ "$CI_JOB_STATUS" = "success" ]; then
        sh src/tg.sh "DO6 CI/CD: Стадия Style успешно завершена!"
      else
        sh src/tg.sh "DO6 CI/CD: Ошибка на стадии Style!"
      fi

integratin-tests:
  stage: test
  tags:
    - test
  script:
    - echo "========================"
    - echo "Проверка тестов в папке cat:"
    - echo "..."
    - cd src/cat
    - make test || { echo "Ошибка! Тесты для cat не прошли!"; exit 1; }
    - echo "========================"
    - echo "Проверка тестов в папке grep:"
    - echo "..."
    - cd ../grep
    - make test || { echo "Ошибка! Тесты для grep не прошли!"; exit 1; }
  after_script:
    - if [ "$CI_JOB_STATUS" = "success" ]; then
        sh src/tg.sh "DO6 CI/CD: Стадия Test успешно завершена!"
      else
        sh src/tg.sh "DO6 CI/CD: Ошибка на стадии Test!"
      fi
  when: on_success

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - cd src
    - ./deploy.sh
  after_script:
    - if [ "$CI_JOB_STATUS" = "success" ]; then
        sh src/tg.sh "DO6 CI/CD: Стадия Deploy успешно завершена!"
      else
        sh src/tg.sh "DO6 CI/CD: Ошибка на стадии Deploy!"
      fi
  when: manual
  dependencies:
    - build_simple_bash_utils
  allow_failure: false 
