stages:
  - build
  - style
  - test
  - deploy

build_simple_bash_utils:
  stage: build
  tags:
    - build
  script:
    - cd src/cat && make s21_cat
    - cd ../grep && make s21_grep
  after_script:
    - sh src/tg.sh || exit 1
  artifacts:
    paths:
      - src/cat/s21_cat
      - src/grep/s21_grep
    expire_in: 30 days

style-test:
  stage: style
  tags:
    - style
  script:
    - cd src
    - ./test_style.sh || exit 1
  after_script:
    - sh src/tg.sh

integratin-tests:
  stage: test
  tags:
    - test
  script:
    - echo "========================"
    - echo "Проверка тестов в папке cat:"
    - echo "..."
    - cd src/cat
    - make test || { echo "Ошибка! Тесты для cat не прошли!"; exit 1; }
    - echo "========================"
    - echo "Проверка тестов в папке grep:"
    - echo "..."
    - cd ../grep
    - make test || { echo "Ошибка! Тесты для grep не прошли!"; exit 1; }
  after_script:
    - sh src/tg.sh || exit 1
  when: on_success

deploy:
  stage: deploy
  tags:
    - deploy
  script:
    - cd src
    - ./deploy.sh
  after_script:
    - sh src/tg.sh || exit 1
  when: manual
  dependencies:
    - build_simple_bash_utils
  allow_failure: false 
